### ISSUE TITLE
無料放送だけ予約する機能

### ISSUE THREAD

**Issue by tsuzu** [musaprg/annict-epgstation-connector#7]
CSのアニマックスとか録画されて困ることがあるので欲しい

**Comment by musaprg** [comment]
無料放送の検索条件をフラグ経由で渡せるようにするので対応できそう。基本無料放送しか録画しないと思うのでデフォは無料放送のみにしておくのが良い気がする。

**Comment by tsuzu** [comment]
https://github.com/musaprg/annict-epgstation-connector/blob/f17ecb0af07311daf4db548590eb934a31590935/internal/syncer/syncer.go#L79

もうなってました。申し訳ない :pray:
